### ISSUE TITLE
求帮忙看个问题

### ISSUE THREAD

**Issue by CZHIC** [BeijiYang/citySelector#5]
VM685:1 thirdScriptError
Cannot read property 'city' of null;at api request success callback function
TypeError: Cannot read property 'city' of null
    at be.setCityCounty (http://127.0.0.1:43215/appservice/pages/switchcity/switchcity.js:161:26)
    at success (http://127.0.0.1:43215/appservice/pages/switchcity/switchcity.js:154:23)

运行时抱这个错时为啥啊，大佬能说说吗？

**Comment by CZHIC** [comment]
哦，是我的腾讯Api的key没有设置webServerApi  权限。。。
